name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Deploy to EC2
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-app:${{ github.event.workflow_run.head_sha }}
          docker stop my-app || true
          docker rm my-app || true
          docker run -d \
            -p 5000:5000 \
            --name my-app \
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-app:${{ github.event.workflow_run.head_sha }}
