name: CI Pipeline
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-app:${{ github.sha }}
          
      - name: Check the tag
        run: echo "${{ github.sha }}"
