name: CI/CD Pipeline
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t my-ci-cd-app .

      # Push to Docker Hub (replace with your credentials)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker tag my-ci-cd-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-ci-cd-app:latest
